name: Hello World
on: push
jobs:
  my_first_job:
    name: My first job
    runs-on: macos-latest # ubuntu-latest 
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: build and run
      env:
        MY_VAR: build and run my project
      run: |
        echo $MY_VAR
        cd basic_skills
        cmake -Bbuild .
        cd build
        make -j12
        ./main
        